---
- name: Add VLANs to device
  hosts: LEAFS
  tasks:
    - name: Add VLAN
      arista.eos.eos_vlans:
        config:
          - name: "VLAN_{{ vlan_id }}"
            vlan_id: "{{ vlan_id }}"
            state: active
        state: merged
