---
- name: Add Users to device
  hosts: all
  tasks:
    - name: Add SSH keys
      arista.eos.eos_user:
        name: tony
        sshkey: PUT_YOUR_PUBLIC_SSH_KEY_HERE
        state: present
    - name: Add user
      arista.eos.eos_user:
        name: tony
        nopassword: true
        privilege: 15
        role: network-admin
        state: present
